id: AE2000296
title: 'The Sealed Quintessence: The Innermost Secret Guru Practice of the Heart-Essence
  of the Vast Expanse'
type: translation
pechas:
- I5188B26C
- ICF24F837
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 13:00:20.896656
  last_modified_at: 2023-01-04 13:00:20.896679
  collections:
  - Longchen Rabjam Series
  - Works of Tibetan Masters
alignment_to_base:
  I5188B26C/F381: A4AB
  ICF24F837/0E75: A4AB
